version: '3.8'

services:
  # 1. MongoDB Database Box
  database:
    image: mongo:latest
    container_name: safegame_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

  # 2. Safegame Node.js Server Box
  app-server:
    image: dldcom/safegame-server:latest
    container_name: safegame_server
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@database:27017/${MONGO_DB}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
    volumes:
      - ./server/public/uploads:/app/server/public/uploads

  # 3. Safegame React Client Box
  client:
    image: dldcom/safegame-client:latest
    container_name: safegame_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app-server

volumes:
  mongo_data:
